version: '3'
services:
  api:
    image: backend-tutorial
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"


networks:
  backend:
    driver: bridge